// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello
List rcpp_hello();
RcppExport SEXP ComputationalGeometry_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}
// WeightedVoronoi
Rcpp::List WeightedVoronoi(const Rcpp::NumericVector& inputX, const Rcpp::NumericVector& inputY);
RcppExport SEXP ComputationalGeometry_WeightedVoronoi(SEXP inputXSEXP, SEXP inputYSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type inputX(inputXSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type inputY(inputYSEXP);
    rcpp_result_gen = Rcpp::wrap(WeightedVoronoi(inputX, inputY));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"ComputationalGeometry_rcpp_hello", (DL_FUNC) &ComputationalGeometry_rcpp_hello, 0},
    {"ComputationalGeometry_WeightedVoronoi", (DL_FUNC) &ComputationalGeometry_WeightedVoronoi, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ComputationalGeometry(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
