# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bounded Weighted Voronoi Diagram
#'
#' Produce a weighted and bounded Voronoi diagram. This is a wrapper for the CGAL library, see \url{http://doc.cgal.org/latest/Apollonius_graph_2/index.html} for algorithm details.
#'
#' @param coordX numeric vector of x coordinates
#' @param coordY numeric vector of y coordinates
#' @param Weights numeric vector of weights
#' @param minX coordinates of bounding rectangle
#' @param minY coordinates of bounding rectangle
#' @param maxX coordinates of bounding rectangle
#' @param maxY coordinates of bounding rectangle
#'
#' @export
BoundedUnweightedVoronoi <- function(coordX, coordY, minX, minY, maxX, maxY) {
    .Call('ComputationalGeometry_BoundedUnweightedVoronoi', PACKAGE = 'ComputationalGeometry', coordX, coordY, minX, minY, maxX, maxY)
}

#' Weighted Voronoi Diagram
#'
#' Produce a weighted Voronoi diagram. This is a wrapper for the CGAL library, see \url{http://doc.cgal.org/latest/Apollonius_graph_2/index.html} for algorithm details.
#'
#' @param coordX numeric vector of x coordinates
#' @param coordY numeric vector of y coordinates
#' @param Weights numeric vector of weights
#'
#' @export
BoundedWeightedVoronoi <- function(coordX, coordY, Weights, minX, minY, maxX, maxY) {
    .Call('ComputationalGeometry_BoundedWeightedVoronoi', PACKAGE = 'ComputationalGeometry', coordX, coordY, Weights, minX, minY, maxX, maxY)
}

#' @export
rcpp_hello <- function() {
    .Call('ComputationalGeometry_rcpp_hello', PACKAGE = 'ComputationalGeometry')
}

#' Voronoi Treemap Algorithm
#'
#' See \url{https://www.stat.auckland.ac.nz/~paul/Reports/VoronoiTreemap/voronoiTreeMap.html} for algorithm details.
#'
#' @param coordX numeric vector of x coordinates
#' @param coordY numeric vector of y coordinates
#' @param Weights numeric vector of weights
#'
#' @export
voronoiTreemap <- function(coordX, coordY, Weights, minX, minY, maxX, maxY) {
    .Call('ComputationalGeometry_voronoiTreemap', PACKAGE = 'ComputationalGeometry', coordX, coordY, Weights, minX, minY, maxX, maxY)
}

#' Unbounded Unweighted Voronoi Diagram
#'
#' Produce a weighted Voronoi diagram. This is a wrapper for the CGAL library, see \url{http://doc.cgal.org/latest/Apollonius_graph_2/index.html} for algorithm details.
#'
#' @param coordX numeric vector of x coordinates
#' @param coordY numeric vector of y coordinates
#'
#' @export
UnboundedUnweightedVoronoi <- function(coordX, coordY) {
    .Call('ComputationalGeometry_UnboundedUnweightedVoronoi', PACKAGE = 'ComputationalGeometry', coordX, coordY)
}

