# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bounded Weighted Voronoi Diagram
#'
#' Produce a weighted and bounded Voronoi diagram. This is a wrapper for the CGAL library, see \url{http://doc.cgal.org/latest/Apollonius_graph_2/index.html} for algorithm details.
#'
#' @param coordX numeric vector of x coordinates
#' @param coordY numeric vector of y coordinates
#' @param Weights numeric vector of weights
#' @param minX coordinates of bounding rectangle
#' @param minY coordinates of bounding rectangle
#' @param maxX coordinates of bounding rectangle
#' @param maxY coordinates of bounding rectangle
#'
#' @export
BoundedWeightedVoronoi <- function(coordX, coordY, Weights, minX, minY, maxX, maxY) {
    .Call('ComputationalGeometry_BoundedWeightedVoronoi', PACKAGE = 'ComputationalGeometry', coordX, coordY, Weights, minX, minY, maxX, maxY)
}

#' @export
rcpp_hello <- function() {
    .Call('ComputationalGeometry_rcpp_hello', PACKAGE = 'ComputationalGeometry')
}

#' Weighted Voronoi Diagram
#'
#' Produce a weighted Voronoi diagram. This is a wrapper for the CGAL library, see \url{http://doc.cgal.org/latest/Apollonius_graph_2/index.html} for algorithm details.
#'
#' @param coordX numeric vector of x coordinates
#' @param coordY numeric vector of y coordinates
#' @param Weights numeric vector of weights
#'
#' @export
WeightedVoronoi <- function(coordX, coordY, Weights) {
    .Call('ComputationalGeometry_WeightedVoronoi', PACKAGE = 'ComputationalGeometry', coordX, coordY, Weights)
}

